// <auto-generated>
// Rewired Constants
// This list was generated on 9/14/2019 12:59:39 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MOVE_HORIZONTAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MOVE_VERTICAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Horizontal")]
        public const int LOOK_HORIZONTAL = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Vertical")]
        public const int LOOK_VERTICAL = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Ready Up")]
        public const int READY_UP = 30;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Unready")]
        public const int UNREADY = 31;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
        public const int PAUSE = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Debug")]
        public const int DEBUG = 32;
        // Hero
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Hero", friendlyName = "Trigger Ability")]
        public const int TRIGGER_HEROABILITY = 23;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Hero", friendlyName = "Transmit Ability")]
        public const int TRANSMIT_ABILITY = 22;
        // Boss
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Boss", friendlyName = "Shoot")]
        public const int SHOOT = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Boss", friendlyName = "TriggerAbility")]
        public const int TRIGGER_BOSSABILITY = 29;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Move Horizontal")]
        public const int UIHORIZONTAL = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Move Vertical")]
        public const int UIVERTICAL = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Submit")]
        public const int UISUBMIT = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int UICANCEL = 12;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
        public const int MENU = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int DEFAULT = 0;
            public const int HERO = 3;
            public const int BOSS = 4;
        }
        public static partial class Keyboard {
            public const int DEFAULT = 0;
        }
        public static partial class Mouse {
            public const int DEFAULT = 0;
        }
        public static partial class CustomController {
            public const int DEFAULT = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int PLAYER0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int PLAYER1 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int PLAYER2 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int PLAYER3 = 3;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
        public const int RULESETHERO = 0;
        public const int RULESETBOSS = 1;
        public const int RULESETMENU = 2;
    }
    public static partial class MapEnablerRuleSet {
    }
}
